# Generated by Django 4.2.7 on 2023-12-06 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Files",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_content", models.BinaryField()),
                (
                    "description",
                    models.CharField(
                        choices=[
                            ("LOG", "log"),
                            ("BINARY", "binary"),
                            ("COMPACT", "compact"),
                            ("LOOSE", "loose"),
                        ],
                        default="LOG",
                        max_length=9,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
