# Generated by Django 4.2.7 on 2023-12-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataPage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="files",
            name="description",
            field=models.CharField(
                choices=[
                    ("LOG", "log"),
                    ("BINARY", "binary"),
                    ("COMPACT", "compact"),
                    ("LOOSE", "loose"),
                ],
                default="LOG",
                max_length=9,
            ),
        ),
    ]
