# Generated by Django 4.2.7 on 2023-12-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataPage", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="files",
            name="file_content",
            field=models.BinaryField(editable=True),
        ),
    ]
