# Generated by Django 4.2.7 on 2023-12-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataPage", "0002_alter_files_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="files",
            name="description",
            field=models.CharField(
                blank=True,
                choices=[
                    ("log", "Log"),
                    ("binary", "Binary"),
                    ("compact", "Compact"),
                    ("loose", "Loose"),
                ],
                default="Log",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="files",
            name="file",
            field=models.BinaryField(),
        ),
    ]
