# Generated by Django 4.2.7 on 2023-12-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataPage", "0003_alter_files_description_alter_files_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="files",
            name="description",
            field=models.CharField(
                choices=[
                    ("LOG", "log"),
                    ("BINARY", "binary"),
                    ("COMPACT", "March"),
                    ("LOOSE", "loose"),
                ],
                default="LOG",
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="files",
            name="file",
            field=models.FileField(upload_to="user_files/"),
        ),
    ]
