# Generated by Django 4.2.7 on 2023-11-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DCR", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userchoices",
            name="weights",
            field=models.JSONField(default=dict),
        ),
    ]
